services:
  mysql:
    image: mysql:8.0
    container_name: mysql-desafio01
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: desafio_01
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./banco_de_dados:/docker-entrypoint-initdb.d  

volumes:
  mysql-data: